/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CdTrendChart: typeof import('./../../src/components/tuning/CdTrendChart.vue')['default']
    ChatCodeBlock: typeof import('./../../src/components/chat/ChatCodeBlock.vue')['default']
    ChatTitle: typeof import('./../../src/components/chat/ChatTitle.vue')['default']
    ContentPart: typeof import('./../../src/components/chat/message/ContentPart.vue')['default']
    ContextUsage: typeof import('./../../src/components/chat/ContextUsage.vue')['default']
    GetCurrentTimePart: typeof import('./../../src/components/chat/message/part/GetCurrentTimePart.vue')['default']
    Indicator: typeof import('./../../src/components/chat/Indicator.vue')['default']
    MessageActions: typeof import('./../../src/components/chat/message/MessageActions.vue')['default']
    MessageContent: typeof import('./../../src/components/chat/message/MessageContent.vue')['default']
    MessageEdit: typeof import('./../../src/components/chat/message/MessageEdit.vue')['default']
    MessageProcess: typeof import('./../../src/components/chat/message/MessageProcess.vue')['default']
    ModelSelect: typeof import('./../../src/components/ModelSelect.vue')['default']
    Navbar: typeof import('./../../src/components/Navbar.vue')['default']
    ProcessStep: typeof import('./../../src/components/chat/message/part/ProcessStep.vue')['default']
    ReasoningPart: typeof import('./../../src/components/chat/message/part/ReasoningPart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextPart: typeof import('./../../src/components/chat/message/part/TextPart.vue')['default']
    ToolOutputPart: typeof import('./../../src/components/chat/message/part/ToolOutputPart.vue')['default']
    ToolPart: typeof import('./../../src/components/chat/message/part/ToolPart.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCollapsible: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UError: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Error.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UserMenu: typeof import('./../../src/components/UserMenu.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
