/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatCodeBlock: typeof import('./../../src/components/chat/ChatCodeBlock.vue')['default']
    ChatTitle: typeof import('./../../src/components/chat/ChatTitle.vue')['default']
    ContextUsage: typeof import('./../../src/components/chat/ContextUsage.vue')['default']
    Indicator: typeof import('./../../src/components/chat/Indicator.vue')['default']
    MessageActions: typeof import('./../../src/components/chat/message/MessageActions.vue')['default']
    MessageContent: typeof import('./../../src/components/chat/message/MessageContent.vue')['default']
    MessageEdit: typeof import('./../../src/components/chat/message/MessageEdit.vue')['default']
    ModelSelect: typeof import('./../../src/components/ModelSelect.vue')['default']
    Navbar: typeof import('./../../src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UChatMessages: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue')['default']
    UChatPrompt: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UChatReasoning: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/ChatReasoning.vue')['default']
    UChatShimmer: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/ChatShimmer.vue')['default']
    UColorModeButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSearch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UError: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Error.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UKbd: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    ULink: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/vue/overrides/vue-router/Link.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelectMenu: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UserMenu: typeof import('./../../src/components/UserMenu.vue')['default']
    USkeleton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_1da80520b25c74306c4893290b5b24c2/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
